### ISSUE TITLE
Completions not working with lifetimes

### ISSUE THREAD

**Issue by krzat** [phildawes/racer#131]
```
struct Foo;
impl Foo {
	fn f1<'a>(self) {}
	fn f2(self) {}
}

fn main() {
	let mut x = Foo;
	x.
}
```

Completion doesn't work if <'a> is present in this code.

**Comment by phildawes** [comment]
Hi @krzat, Thanks for the bug report
I fixed this last night but forgot to push, oops! The single-quote string masking code was getting confused with lifetimes, it should work now

**Comment by krzat** [comment]
Cool, thanks. Completion vector takes like 5 seconds though. I will think
about caching maybe, it should be pretty easy to do per file and using last
modified date to keep it fresh.

**Comment by phildawes** [comment]
Hi @krzat. Wow that sounds like a long time. Is this on a release build? (cargo build --release).

How long does this take on your machine?
```rust
let v = Vec::new();
v.<tab>
```

Caching may be the solution, but I'd like to profile first; I suspect racer is doing some unnecessary work in the area of following glob imports. 
(N.B. I don't think caching is as easy as you think because racer doesn't parse/type-infer whole files)

**Comment by krzat** [comment]
Yep, I didn't notice it was debug build. On release it's not bad:

real 0m1.135s

user 0m0.501s

sys 0m0.607s


I will think about the caching, for example when you do let src =
racer::load_file(&m.filepath); it seems like a good occasion to cache
everything necessary, so you don't have to open it again (unless it
changes).
