### ISSUE TITLE
how to enable logging?

### ISSUE THREAD

**Issue by MarkSwanson** [phildawes/racer#192]
I'd like to take a stab at modifying racer, but I can't seem to get logging to work.

How do you configure things so debug!() writes the logs to a file somewhere?

Thanks.

**Comment by phildawes** [comment]
Hi Mark,
You have to set the environment variable RUST_LOG=debug  (or RUST_LOG=racer=debug if you only only want the logging from the racer crate).
Hmmm... Now that you mention it I can't find RUST_LOG documented in the rust docs 

Cheers,

Phil

**Comment by phildawes** [comment]
Oops - closed by mistake

**Comment by JustAPerson** [comment]
@phildawes 
This has been deprecated in the standard distribution, see [this comment](https://github.com/rust-lang/rust/issues/3309#issuecomment-68273049).
This functionality has moved to the [log](https://crates.io/crates/log) and [env_logger](https://crates.io/crates/env_logger) crates. To explain, the `debug!()`-esque macros have moved to the `log` crate, which provides a general logging API. However, it does not perform the actual logging; that requires a backend implementation of this API. `env_logger` is probably the simplest of these backends. Another one worth looking at is [log4rs](https://crates.io/crates/log4rs), which is more flexible and configured by a .toml file instead of the `RUST_LOG` environment variable.
