### ISSUE TITLE
Enum type matched twice

### ISSUE THREAD

**Issue by andersforsgren** [phildawes/racer#238]
Input:

    enum Zzz {
       X,
       Y,
    }

    fn main() {
        Z
    }

Input is with \r\n linebreaks, so literally `enum Zzz {\r\n   X,\r\n   Y,\r\n}\r\n\r\nfn main() {\r\n    Z\r\n}`. 

Command line

   complete 7 5 C:\temp\test.rs
 
Output:

    PREFIX 4,5,Z
    MATCH Zzz,1,5,C:\temp\test.rs,Enum,enum Zzz {
    MATCH Zzz,1,5,C:\temp\test.rs,Enum,enum Zzz {

I suspect (but I'm not sure) that the second line should not be output?

**Comment by phildawes** [comment]
Hi @andersforsgren. Sorry I haven't got to look at this yet, will try and take a look tonight.
Cheers, Phil

**Comment by phildawes** [comment]
Wow, this turned out to be a tricky bug to track down. Racer does two passes when searching a scope, one backwards from point and one forwards (so that it can track let expressions in the right order). It uses a rust statement iterator to do the passes, but I had marked StmtIndicesIter 'Copy', which meant in the for-loops racer was getting a fresh copied statement iterator each time, causing it to iterate the statements twice.
The fix was to use a mutable reference for the loops rather than using the iterator by value (and implicitly copying it).
Thanks very much for the bug report @andersforsgren!
