### ISSUE TITLE
Stack overflow on completion (when function and mod are named the same)

### ISSUE THREAD

**Issue by bluss** [phildawes/racer#354]
I have a project using itertools. Completing for example `itertools::I` works as expected, but `itertools::` completes to nothing. Further research shows it stack overflows when given this completion. [RUST_LOG=debug output is here](https://gist.github.com/bluss/2973167c5cd022dcf6ca).

It was me that replaced $HOME into the logfile.

**Comment by bluss** [comment]
A closer look at the log reveals that it looks like the completion for `itertools::times` that runs in an infinite loop. It's just a function. There's a type of the same name but titlecase (`Times`).

**Comment by bluss** [comment]
Oh and itertools::times is both a private module and a function... that must be it

Here's a minimal testcase:

`testcase.rs`
```rust
pub use times::times;

mod times {
    pub fn times() -> Times { Times }
    pub struct Times;
}

fn main() {
    self::
}
```

stack overflow with completion command to complete at `self::`.
```
racer complete 9 10 testcase.rs
```

**Comment by phildawes** [comment]
Thanks very much for the concise testcase @bluss, I'll take a look

**Comment by phildawes** [comment]
I took a quick look, it looks like even
```
pub use times::times;
```
with `racer find-definition 1 17 testcase.rs` is enough to trip this issue. The problem is that racer searches for `times::times`, decomposes the search into 'find(find("times"), "times")', and then immediately finds the statement again when searching for the outer 'times' module, which triggers a search for `times::times`....

I'm going to have to think hard about the best way to solve this issue.

**Comment by bluss** [comment]
Triage: Still exists in racer as of today, after 1.2.10 at commit b36a9a6af862a63db9397e76abc3cb2013751b8d

itertools suffers from this in version 0.5.0 and [worked around](https://github.com/bluss/rust-itertools/commit/670e844272780d9d9bc763b061e73d5813777484) this issue in release 0.5.1

**Comment by jwilm** [comment]
Hi @bluss,

I've [spent a few hours](https://github.com/phildawes/racer/pull/479) looking into this issue in the past, but it's not particularly straight-forward to fix. Basically, the nameres just recurses indefinitely, and some kind of recursion guard needs to be implemented. Hopefully I'll have time to dig into it again soon; I was hoping for last weekend but that didn't pan out.

This is the number one issue in Racer right now. Nothing else breaks in such a spectacular fashion.

**Comment by bluss** [comment]
Thanks for the update. I suspect it might affect many crates? If only the failure mode were more apparent, more of them would work around it.

Writing `pub use kmerge::kmerge;` in my own code didn't feel particularly pretty either, so I didn't take for granted that Rust would support such name clashes.

**Comment by jwilm** [comment]
There's been quite a few reports with different crates exhibiting this issue; seems like yes it affects many. A short term bandaid might be to try skipping the completion all together if it looks like `use thing::thing` so that at least server processes wouldn't crash.

I agree that the pattern doesn't read nicely due to redundancy.

**Comment by jwilm** [comment]
Going to have a release out shortly with the fix for this.

**Comment by bluss** [comment]
Thanks!
