### ISSUE TITLE
Racer stopped working on Vim with git head build

### ISSUE THREAD

**Issue by gaveen** [phildawes/racer#386]
**Env**
Vim: 7.4 (Included patches: 1-207, 209-801, 803-808, 810-827) with vim-plug
OS: Fedora 22 (x86_64) Linux
Racer: git head (d0c9a10fe4605ad3b1f5931f01409616e84fc9d2)
Rust: 1.2.0

**Config snippets**
_[.vimrc]_
" Plugin definitions for [junegunn/vim-plug](https://github.com/junegunn/vim-plug). Also tried without lazy loading rust.vim 
Plug 'rust-lang/rust.vim',            {'for': 'rust'}
Plug 'phildawes/racer',               {'for': 'rust'}

" Both following g:racer_cmd configs were tested individually
"let g:racer_cmd = "/home/xxxxxx/.vim/bundle/racer/target/release/racer"
let g:racer_cmd = "/home/xxxxxx/Apps/vimfiles/.vim/bundle/racer/target/release/racer"
let $RUST_SRC_PATH="/home/xxxxxx/Software/builds/rust/rustc-1.2.0/src"

_[.bash_profile]_
export RUST_SRC_PATH=$HOME/Software/builds/rust/rustc-1.2.0/src

**Description**
After #255 was closed, I had been using racer, but I update racer (and vim) and built recently which seems to have broken behaviour. Racer works as expected in the command line, but fails to provide _some_ completions inside Vim.

**Expected behaviour**
Enter a partial statement in Insert mode and press C-x-C-o. Auto-complete suggestions should be listed.

**Observed behaviour**
When trying to auto-complete _some_ partial entries with C-x-C-o, I get the error message:
"-- Omni completion (^O^N^P) Pattern not found"
_e.g. 1:_ [Vim] std::io:: --> C-x-C-o ==> completion suggestion menu
_e.g. 2:_ [Vim] std::io::B --> C-x-C-o ==> "-- Omni completion (^O^N^P) Pattern not found"
_e.g. 3:_ [CLI] ./.vim/bundle/racer/target/release/racer complete std::io::B ==> suggestions list

**Additional details**
Vim version was updated to the latest provided by OS vendor recently. Therefore the only things that changed were the vim version and racer version (no vim or bash config changes).

**Comment by BonsaiDen** [comment]
This is an issue with omnicomplete (?) removing the current word from the buffer before the auto complete function is run (racer copies for the current buffer contents from insert mode into a tmpfile in order to perform completion)

If you buffer contains:

```
let foo = some_
```

Then racer will only see:

```
let foo = 
```
once you try to complete `some_`, this will cause a out of bounds panic when running the `racer` command with the no longer valid `col` value of `15`.

Here's a patched [`racer.vim`](https://gist.github.com/BonsaiDen/fa225703bc1b497230aa) which implements a workaround by using the supplied `base` value from omnicomplete and re-appending that to the current line before writing the buffer contents to the tmpfile. 

I can open a PR with the changes if this works out for other folks too.
