### ISSUE TITLE
http protocol for rustc daemon

### ISSUE THREAD

**Issue by phildawes** [phildawes/racer#457]
Hi @jwilm,

As per [my post yesterday](http://phildawes.net/blog/2015/12/29/racer-update-6/) I'm putting together a daemon to provide rustc based type inference for racer. I intend to use http and wondered if you had any opinions based on your experience with the ycmd protocol and Racerd. 

Glancing over the ycmd protocol I was surprised that it isn't more RESTy, or at least that it doesn't use GET more. It seems a shame not to be able to use curl to perform a query or paste a query into a browser and eyeball the results. 

What's your take? Thanks!

**Comment by jwilm** [comment]
Hey @phildawes 

Thanks for the mention in your post :smile:. I just read through it; rustc-based type inference is exciting! HTTP is a fantastic choice for these services - every language has some sort of http library to query with, it's highly parallelizable, and developers are very comfortable working with it.

Although inspired by YCM, the protocol racerd speaks is actually independent of the YCM protocol and contains no YCM specific functionality. `POST` endpoints in this case are nice because the large chunk of data that gets sent to the server does not need URL encoding as they would if sent via GET. The endpoints are still queryable, too. See [the cURL command](https://github.com/jwilm/racerd/blob/master/docs/API.md#curl-command) sections in the [racerd API docs](https://github.com/jwilm/racerd/blob/master/docs/API.md). _racerd_ offers a status endpoint `/ping` via `GET` which is critical for consumers to know when the service is available.

Architecturally, I cannot stress enough how important it is to separate out the semantic analysis (in this case just the type inference) code from the HTTP wrapper and command line API. I would go as far to say that the library should be a separate project from the executable. In the case of racerd, this allows a consumer to integrate at any level - command line via the executable, as a library via starting the HTTP service, or directly with a service provider thereby circumventing the HTTP server all together.

You mentioned something about building out this feature as a project separate from racer. Is that really necessary? Could the rustc type-inference instead be feature-gated within racer? The default racer build would still be trivial on stable/whatever, and then users can "just" opt-in to an advanced build. The downside I see with splitting it out is fragmentation of racer functionality (eg. now users need `racer` and `racer-rustc-type-infer`). I would also be hesitant about having the `racer` and rustc inference integration be via HTTP. For intralibrary communication, HTTP would be magnitudes slower than directly through the ABI.

One final question - why is the initial plan to make a rustc daemon? It was mentioned sort of matter-of-factly in the blog post as _the_ solution. Just curious :blush:.

Once Rust YCM is launched, I would be happy to help out with the rustcd project. I think I've got some relevant experience :wink:.

**Comment by phildawes** [comment]
Hi @jwilm,

I'm was trying to address a couple of problems with the typeck daemon thing:

 1. Not having to bind racer to a specific version of rust. 
 1. Being able to experiment without affecting existing racer code, users and plugins

The rustc api is unstable and currently in a state of flux: the compiler team are working hard to implement MIR and incremental compilation features and the apis change frequently (sometimes multiple times a week). Tracking rust nightly in this environment will generate a bunch of work (racer used to do this with libsyntax pre-1.0 before syntex_syntax came along), and tracking beta or stable requires special hacks[1] 

A separate daemon might not be the best solution though. hmmmm.. I'll sleep on it and reply more in the morning

[1] hack: if you grep the rustc lib binary you can extract a secret date string that lets you unlock the unstable functionality in a stable build

**Comment by LeDominik** [comment]
Hi @phildawes -- maybe I'm a bit naive here, but isn't the new [Language Service Protocol](https://github.com/Microsoft/language-server-protocol) the ideal (light) IDE-integration path going forward? I commented at [racerd](https://github.com/jwilm/racerd/issues/49) the same thing but of course direct integration would be super-awesome...

There's already [a few implementations](https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations)

**Comment by phildawes** [comment]
I hadn't seen this. Thanks Dominik I'll check it out

**Comment by jwilm** [comment]
At this point, racer is just focused on supporting RLS by fixing bugs and making improvements where there is a need from RLS. RLS implements the LSP and is partially powered by racer.
