### ISSUE TITLE
racer only returns the first line of function signatures

### ISSUE THREAD

**Issue by Wilfred** [phildawes/racer#512]
Given the following code:

```rust
fn add_nums(x: i64,
            y: i64)
            -> i64 {
    x + y
}

fn main() {
    add_nums(1, 2);
}
```

Racer returns:

```
$ racer complete 8 7 foo.rs     
PREFIX 4,7,add
MATCH add_nums,1,3,foo.rs,Function,fn add_nums(x: i64,
END
```

Ideally racer would return the whole function signature.

**Comment by jwilm** [comment]
Is this only an issue on the racer cli? I received a [patch on racerd](https://github.com/jwilm/racerd/pull/22) recently which collapsed such functions into a single line for display.

**Comment by phildawes** [comment]
(thanks @Wilfred )
Hi @jwilm, I think this is an issue with racer: the contextstr for the fn doesn't actually contain all the arguments since it chops them off after the first line. (the patch to racerd collapses the contextstr into one line, but in this case I don't think the information is there to collapse)

I think this should be a straightforward patch to make if somebody wants to have a go. I think it is the  'match_fn' function that needs changing

**Comment by alobb** [comment]
@phildawes 
I've almost got a PR ready for this, but I have a few clarification questions:

The bug manifests at matchers.rs:594, which is the following line:
`contextstr: first_line(blob)`
so a simple solution seems to be to, instead of searching through `blob` for the first newline, search for the first open curly bracket.  However, not knowing how `blob` was created, is it guaranteed that blob starts with the function definition?
Once the full function signature is found, should newline characters be stripped, and sequences of spaces be converted to 1 space?

Finally, searching through the blob for the first line seems to be common between most, if not all of the `match_*` functions in matchers.rs.  Should this be changed elsewhere as well?

**Comment by phildawes** [comment]
Hi Aaron,

(Sorry for the brief reply, am on my mobile. ) Cool! I think the answer to
all your questions is yes. The one line thing was just a short term hack
that has lasted longer than it was originally intended it to. (Racer has a
bunch of that kind of thing)
