### ISSUE TITLE
Crash on completion

### ISSUE THREAD

**Issue by cyplo** [phildawes/racer#615]
Hello !

It seems that racer crashes after the following:

    git clone https://github.com/cyplo/crustylogstream.git
    cd crustylogstream
    git checkout racer_crash
    racer complete 9 34 ./src/parser.rs
    PREFIX 34,34,

    thread 'searcher' has overflowed its stack
    fatal runtime error: stack overflow
    [1]    30520 abort (core dumped)  racer complete 9 34 ./src/parser.rs

Checked both the version from the crates.io (racer 1.2.10) as well as the one compiled from current master (e5e664a ).

I compiled the debug version and loaded into gdb as well, please find the session log attached.
[gdb_session.txt](https://github.com/phildawes/racer/files/465878/gdb_session.txt)

Please let me know if you need anything more. In the meantime I will try to see if I can come up with the fix. 

Thank you and have a great day !

**Comment by yodalee** [comment]
I cannot re-create the crash on my computer. My racer ends with no matching result.

**Comment by cyplo** [comment]
Hi !

Thank you for trying out ! I will see if this still crashes for me on the newest master. If so I will try to get you a docker image that reproduces. Would that be helpful ? Thanks !

**Comment by yodalee** [comment]
I can reproduce this, and actually I think PR #479 is trying to deal with similar problem (stack overflow).

**Comment by cyplo** [comment]
Oh, sorry, misunderstood that. Thank you !

**Comment by jwilm** [comment]
Sorry for the delayed response, and thanks for posting the issue!

@yodalee is right; this should be fixed by #479 once I can make some time to dig into it. This is actually a major issue for programs like `racerd` and the `RLS` folks since stack overflows are unrecoverable. I'm planning to come back to this issue on Sunday and will hopefully have some good news next week.

This looks like the same problem as the other issues; it's trying to complete on a module that contains a function with the same name and recurses indefinitely.

Closing as dupe of #354
