### ISSUE TITLE
__imp___acrt_iob_func linking errors under msys2

### ISSUE THREAD

**Issue by Jimmio92** [phildawes/racer#919]
Hello,

I am trying to build racer from master branch (pulled yesterday) and it seems to be linking both the GNU C library like it should as well as MSVCRT.. and I'm not sure if that's where the problem lies. Basically, it seems this error occurs when a library is built with MSVC tools prior to VS2015 and then used in VS2015.. It also seems to pop up only in a few curl functions. Any ideas?

**Comment by kngwyu** [comment]
Hmm... It's upstream issue so I'm not sure I can handle it :sweat: 
Now I updated cargo so could you please try to build once more?
But, in the long run, it seems to be better to use `cargo metadata` as subprocess :slightly_frowning_face:

**Comment by Jimmio92** [comment]
Full build log: [buildlog.txt](https://github.com/racer-rust/racer/files/2291667/buildlog.txt)

Nightly Rust. Master branch here. Msys2 up to date. GCC 8.2.0. Windows 10 x64 in a unix-like bash environment, basically.

**Comment by crlf0710** [comment]
@Jimmio92 This has been the case for quite a while now. It's because MSYS2 ships GCC 8.x, and Rust itself ships GCC 7.x. I have some experience dealing with this.

So basically you have two ways to workaround this issue.
1. Somehow get yourself an environment the same with those mingw-build files Rust ships, e.g. GCC 7.x etc.. (Hard)

2. a. remove rust-mingw component. (edit multirust-channel-manifest.toml to change rust-mingw from component to extensions, then rustup component remove rust-mingw).
    b. replace crt2.o and crt2dll.o with the ones from MINGW64/MINGW32 of MSYS2.
    c. build your crate.

This works until you do a `rustup update` then rust-mingw will be back, and you'll have to start over.

**Comment by Jimmio92** [comment]
crt2.o and crt2dll.o are no longer the name of the now multiple files named crtbegin and crtend, plus some mathematical section of the runtime. So.. I don't know what to do. I guess building Rust from source in this environment would alleviate this problem?

**Comment by crlf0710** [comment]
@Jimmio92 those files still exists. there was a typo however, it's called <del>crt2dll.o</del> **dllcrt2.o** .   crtbegin and crtend files do exists, but they're unrelated.

They're located at(taking 64-bit example on my machine):
```
/mingw64/x86_64-w64-mingw32/lib/crt2.o
/mingw64/x86_64-w64-mingw32/lib/dllcrt2.o
```
And they come with `mingw-w64-x86_64-crt-git 6.0.0.5193.a081b583-1` in MSYS2 package on my machine.

You should use them to replace 
`<somewhere>\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\crt2.o`

`<somewhere>\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\dllcrt2.o`

**Comment by mati865** [comment]
@crlf0710 in fact this is because Rust GCC was build with way older mingw-w64 than MSYS2 (GCC version doesn't matter).
