### ISSUE TITLE
Split racer into executable and library.

### ISSUE THREAD

**Issue by dradtke** [phildawes/racer#94]
I have a proof-of-concept for this set up in my [fork](https://github.com/dradtke/racer), but it's only good enough to compile at this point and could probably use some additional refactoring and/or renaming.

My motivation for this is to let the library contain the bulk of the logic and heavy lifting so that multiple clients can target the same functionality. The existing racer client is nice for text editors that execute it directly, but it would be nice to have support for a client that can do things like integrate with gnome-code-assistance by communicating over DBus rather than standard output and arguments to `main`, and I'm sure there are other use cases where this would be nice to have as well.

**Comment by Valloric** [comment]
Yeah, ycmd needs a library interface as well. Relevant issue https://github.com/phildawes/racer/issues/109.

**Comment by Valloric** [comment]
I've looked a bit into how the [racer.vim](https://github.com/phildawes/racer/blob/master/plugin/racer.vim) integration works and I'm afraid I can't integrate racer into ycmd until racer has a library interface. The current vim integration saves the active buffer to a temp file so that racer can see the latest state of the buffer. This is a solved problem with ycmd; the YCM client sends the current buffer state to the server and the server passes it to the completion engines.

Passing the state of the buffer through the filesystem (which would be necessary if using racer-the-binary) results in terrible performance; this goes on top of the perf hit from the process setup/teardown, the serialization/deserialization round-trip through stdout and the lack of any AST caching because racer sees each completion request in complete isolation from any previous ones.

This results in multi-second latency to get completions on my fairly beefy workstation. 

The above perf problems would go away with a library design; when that happens, I'd be ecstatic about integrating racer into YCM (through ycmd).

**Comment by phildawes** [comment]
Hi Valloric,
Multi-second latency sounds pretty awful, it sounds like something might be wrong.
I get ~200ms completions on my laptop with racer. E.g.

$ time ~/src/rust/racer/bin/racer complete 4 17 /tmp/e.rs
PREFIX 17,17,
MATCH new,163,11,/usr/local/src/rust/src/libcollections/vec.rs,Function,pub fn new() -> Vec<T> {
MATCH with_capacity,198,11,/usr/local/src/rust/src/libcollections/vec.rs,Function,pub fn with_capacity(capacity: uint) -> Vec<T> {

real	0m0.121s
user	0m0.032s
sys	0m0.088s

Cheers,

Phil

**Comment by phildawes** [comment]
Hello! I published the first cut of a library earlier this week: https://crates.io/crates/racer

This has had practically no testing so treat it as a starting point for feedback. 
E.g. here's a client
```
extern crate racer;

use racer::{complete_from_file, coords_to_point, point_to_coords};
use std::io::{File, BufferedReader};

fn main() {
    let filepath = Path::new("/tmp/e.rs");

    // In this case I'm loading the file from disk, but...
    let rawbytes = BufferedReader::new(File::open(&filepath)).read_to_end().unwrap();
    let src = String::from_utf8(rawbytes).unwrap();
    let mut completions = complete_from_file(&*src, &filepath, coords_to_point(&*src, 4, 17));
    for match_ in completions {
        let rawbytes = BufferedReader::new(File::open(&match_.filepath)).read_to_end().unwrap();
        let src = String::from_utf8(rawbytes).unwrap();
        println!("{:?}, {:?}, {:?}",match_.matchstr, match_.filepath, 
                 point_to_coords(&*src, match_.point));
        
    }
}
```

**Comment by phildawes** [comment]
Actually, scratch that. There are some real problems with doing this without a temporary file. I'll try and fix and then comment back

**Comment by Valloric** [comment]
@phildawes Thanks for working on this! It seems you have some issues to shake out in the code; feel free to give a heads-up when you have something working.

For inspiration, you may want to look at [the API that libclang provides](http://clang.llvm.org/doxygen/group__CINDEX.html). It's more low-level because of the C interface, but the logical abstractions it provides are solid. For example usage of the libclang API for code-completion, you can see how ycmd uses it [here](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/ClangCompleter/TranslationUnit.cpp).

**Comment by tafia** [comment]
@phildawes what exactly is the issue in not using temporary files ?

**Comment by phildawes** [comment]
Hi @tafia,

The problem is that racer loads files from disk as it searches. In the above case even though the code text is being passed in, racer attempts to load the 'file' later if it needs to recursively resolve a path or type in the same text. This means that it fails if the code being passed as text doesn't match what's on the filesystem. Does that make sense?

I guess instead racer should be holding a cache of loaded code during the search. This would need to be passed between threads in some way, or maybe a locked struct.

I haven't done this yet because I'm planning on going the direction of using rustc more to incrementally compile to resolve types, so the shape of this whole loading thing might evolve with that. 

I guess the other fix for the short term would be to just stick with temporary files even when racer is used as a library and have the api just pass in a filename. That's probably easiest for now but I suspect not what ide/plugin developers would want. 

Cheers,

Phil

**Comment by oblitum** [comment]
@phildawes I'd like just to point out that the libclang completion interface is not ideal, in case you're going to use it for inspiration at any time. The defect I think it has is to provide a single form of obtaining completions. `clang_codeCompleteAt` currently fits well for obtaining suggestions of text that may fit a _locus_ but, for example, it's not ideal when obtaining function parameters after `(` because with the prototypes comes all the stuff that may fit as arguments at the call site. So both call signature information _and_ suggestions for what may be an argument comes in the same request. This is not ideal because function prototype information is much less than the other random suggestions, and frequently you may be just interested in the prototypes, but the interface becomes slow with the extra information, since it provides only one way of obtaining information.

**Comment by Valloric** [comment]
@oblitum You make a good point, but there's nothing stopping racer from having additional API methods for getting function params etc. Also, racer is at a pretty early stage where just having an API function (instead of a command-line setup) that will provide semantic names available at a cursor location (while doing proper caching etc) would be a big jump.

"Walk before you run" sort of thing.

**Comment by oblitum** [comment]
@Valloric Indeed, I'd just like to point out this to bring awareness on the issue so it's avoided.

**Comment by oblitum** [comment]
@Valloric early planning this can avoid a lot of internal refactoring.

**Comment by jwilm** [comment]
What work is needed to get the racer library ready? I see that the racer lib PR was merged, but this issue is still outstanding.

**Comment by rubdos** [comment]
I basically have the same question as @jwilm had a month ago ; what work needs to be done to get the library ready? It's a blocker for https://github.com/Valloric/YouCompleteMe/issues/1297 and I'd *love* to get that running!

**Comment by dbrgn** [comment]
Same here.

**Comment by phildawes** [comment]
Hello,

Racer should be the right shape to be used as a library now in theory, although in practice none of the plugins do this at the moment. You can also run racer in daemon mode where it will run as a longer running process.

I am currently working on integration with rustc, so my spare time is elsewhere at the moment but if somebody fancies picking this up then that would be cool.

**Comment by Valloric** [comment]
Thanks @phildawes for working on this!

If someone wants to see racer support in YCM and is willing to get their hands dirty, the next step would be to wrap racer in an HTTP+JSON server. A small Rust REST server. If you get that done, I'll be happy to write the ycmd glue code that talks to it; I unfortunately don't have time to write the server as well.

For inspiration on what the REST API should look like, run the [ycmd example client](https://github.com/Valloric/ycmd/tree/master/examples) to see the requests & responses. The API should in fact be simpler than that since only one language needs to be supported.

**Comment by jwilm** [comment]
@Valloric I have time to build that server! I'm going to look at the reference you provided and probably have some questions for you before getting started. For anyone else interested in progress/contributing, the code will be [here](https://github.com/jwilm/ycmd-racer).

@phildawes thanks for supporting racer integrations! Should this issue be closed if racer as a library is done?

**Comment by dbrgn** [comment]
Wohoo! Looking forward to it. Thanks @jwilm!

**Comment by phildawes** [comment]
@jwilm I'm hesitant to say that racer as a library is done because in practice it hasn't really been used in this mode and there are bound to be issues. Closing the issue for now though

**Comment by Valloric** [comment]
@jwilm See my email address [on my about page](https://val.markovic.io/about). Shoot me an email and I'll add you to the ycm-dev list where YCM devs hang around. We'll be more than happy to answer any questions you might have.
